services:
  app:
    build: ./
    env_file: ./.env
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres:17
    container_name: database
    hostname: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /var/lib/postgresql/tech_data:/var/lib/postgresql/tech_data
    ports:
      - "5432:5432"
